blog/room/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.rooms, name='rooms'),
    path('<slug:slug>/', views.room, name='room'),
]

blog/urls.py
from django.urls import path
from . import views

from .feeds import LatestPostsFeed

app_name = 'blog'

urlpatterns = [
    # post views
    path('', views.post_list, name='post_list'),
    # path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),
]

newsite/urls.py
from django.urls import path, include
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap

from blog.sitemap import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sign.urls')),
    path('rooms/', include('room.urls')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap')
]

blog/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User

from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset()\
                          .filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,
                            unique_for_date='publish')
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year, self.publish.month, self.publish.day, self.slug])


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)

blog/room/models.py
from django.contrib.auth.models import User
from django.db import models


class Room(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)


class Message(models.Model):
    room = models.ForeignKey(Room, related_name='messages', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='messages', on_delete=models.CASCADE)
    content = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('date_added',)

blog/forms.py
from django import forms

from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')


class SearchForm(forms.Form):
    query = forms.CharField()

blog/room/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from .models import Room, Message


@login_required
def rooms(request):
    rooms = Room.objects.all()

    return render(request, 'room/rooms.html', {'rooms': rooms})


@login_required
def room(request, slug):
    room = Room.objects.get(slug=slug)
    messages = Message.objects.filter(room=room)[0:25]

    return render(request, 'room/room.html', {'room': room, 'messages': messages})

blog/views.py
from django.core.mail import send_mail
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView
from django.db.models import Count
from django.contrib.postgres.search import TrigramSimilarity

from taggit.models import Tag


from .models import Post
from .forms import EmailPostForm, CommentForm, SearchForm


def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 3)  # 3 поста на каждой странице
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # Если страница не является целым числом, поставим первую страницу
        posts = paginator.page(1)
    except EmptyPage:
        # Если страница больше максимальной, доставить последнюю страницу результатов
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post/list.html', {'page': page, 'posts': posts, 'tag': tag})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post, status='published', publish__year=year, publish__month=month, publish__day=day)
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]
    comments = post.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()
    return render(request,
                  'blog/post/detail.html',
                  {'post': post,
                   'comments': comments,
                   'new_comment': new_comment,
                   'comment_form': comment_form,
                   'similar_posts': similar_posts})


def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False
    form = EmailPostForm(request.POST)
    if request.method == 'POST':

        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) recommends you reading " {}"'.format(cd['name'], cd['email'], post.title)
            message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(post.title, post_url, cd['name'], cd['comments'])
            send_mail(subject, message, 'admin@myblog.com', [cd['to']])
            sent = True
        else:
            form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent': sent})


def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results = Post.objects.annotate(
                similarity=TrigramSimilarity('title', query),
            ).filter(similarity__gt=0.3).order_by('-similarity')
    return render(request,
                  'blog/post/search.html',
                  {'form': form,
                   'query': query,
                   'results': results})

templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}
  
{% block title %}{{ post.title }}{% endblock %}  
  
{% block content %}  
  <h1 class=" text-white text-center lg:text-2xl bg-teal-600">{{ post.title }}</h1>
  <p class="date text-black text-center">
    Published {{ post.publish }} by {{ post.author }}  
  </p>  
  <div class ="text-black text-center">{{ post.body|markdown }}</div>
<p>
  <a class="text-white text-center bg-teal-700 lg:text-2xl hover:bg-teal-700" href="{% url 'blog:post_share' post.id %}">
    Share this post
  </a>
</p>

<h2 class=" text-grey lg:text-2xl bg-teal-600">Similar posts:</h2>
{% for post in similar_posts %}
    <p>
        <a class="text-white lg:text-xl hover:text-gray-200" href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </p>
 {% empty %}
  <p class=" text-grey lg:text-2xl bg-teal-600">There are no similar posts yet.</p>
{% endfor %}



{% for comment in comments %}
  <div class="comment bg-teal-600">
    <p class="info text-black lg:text-2xl text-center">
      Comment {{ forloop.counter }} by {{ comment.name }}
      {{ comment.created }}
    </p>
  {{ comment.body|linebreaks }}
  </div>
{% empty %}
  <p>There are no comments yet.</p>
{% endfor %}

{% with comments.count as total_comments %}
  <h2>
    {{ total_comments }} comment{{ total_comments|pluralize }}
  </h2>

{% if new_comment %}
  <h2 class ="text-black text-center">Your comment has been added.</h2>
{% else %}
  <h2 class ="text-black lg:text-2xl text-center">Add a new comment:</h2>
  <form class ="text-black lg:text-2xl text-center" action="." method="post">
    <div>{{ comment_form.as_p }}</div>
    {% csrf_token %}
    <p><input class="px-5 py-3 rounded-xl text-white text-center bg-teal-700 lg:text-2xl hover:bg-teal-700" type="submit" value="Add comment"></p>
  </form>
{% endif %}
{% endwith %}
{% endblock %}

templates/blog/post/latest_posts.html
<ul>
{% for post in latest_posts %}
  <li>
    <a class="text-3xl lg:text-3xl text-white" href="{{ post.get_absolute_url }}">{{ post.title }}</a>
  </li>
{% endfor %}
</ul>

templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}
  
{% block title %}My Blog{% endblock %}  
  
{% block content %}  
  <h1 class="text-white lg:text-4xl hover:text-gray-200"><a href="{% url "blog:post_list" %}">My blog</h1>

  {% if tag %}
    <h2 >Posts tagged with "{{ tag.name }}"</h2>
  {% endif %}

  {% for post in posts %}
    <h2>
      <a class="text-white lg:text-3xl hover:text-gray-200" href="{{ post.get_absolute_url }}">
       {{ post.title }}
      </a>
      <p class="tags text-white lg:text-2xl hover:text-gray-400" >
  Tags:
  {% for tag in post.tags.all %}
    <a href="{% url "blog:post_list_by_tag" tag.slug %}">
      {{ tag.name }}
    </a>
    {% if not forloop.last %}, {% endif %}
  {% endfor %}
</p>
    </h2 >
    <p class ="date text-grey">
      Published {{ post.publish }} by {{ post.author }}
    </p>
<div class ="text-black">{{ post.body|markdown|truncatewords:30 }}</div>

  {% endfor %}
  {% include "../pagination.html" with page=posts %}
{% endblock %}

templates/blog/post/search.html
{% extends "blog/base.html" %}

{% block title %}Search{% endblock %}

{% block content %}
  {% if query %}
    <h1 class="text-white lg:text-3xl">Posts containing "{{ query }}"</h1>
    <h3>
      {% with results.count as total_results %}
      <p class="text-black">Found {{ total_results }} result{{ total_results|pluralize }}:</p>
      {% endwith %}
    </h3>
    {% for post in results %}
      <h4><a class="text-white lg:text-3xl hover:text-gray-200" href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
      <p class="text-black">{{ post.body|truncatewords:5 }}</p>
    {% empty %}
      <p>There are no results for your query.</p>
    {% endfor %}
    <p><a class="text-white text-center bg-teal-700 lg:text-2xl hover:bg-teal-700" href="{% url "blog:post_search" %}">Search again</a></p>
  {% else %}
    <h1>Search for posts</h1>
    <form action="." method="get">
      {{ form.as_p }}
      <input class="px-2 py-2 rounded-l text-white text-center bg-teal-600 lg:text-4xl hover:bg-teal-700" type="submit" value="Search">
    </form>
  {% endif %}
{% endblock %}

templates/blog/post/share.html
{% extends "blog/base.html" %}  
  
{% block title %}Share a post{% endblock %}  
  
{% block content %}  
  {% if sent %}  
    <h1 class ="text-black lg:text-2xl">E-mail successfully sent</h1>
    <p class ="text-black lg:text-2xl">
      "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.  
    </p>  
  {% else %}  
    <h1 class ="text-black text-center lg:text-3xl">Share "{{ post.title }}" by e-mail</h1>
    <form class ="text-black lg:text-2xl" action="." method="post">
      {{ form.as_p }}  
      {% csrf_token %}  
      <input class ="text-black lg:text-2xl" type="submit" value="Send e-mail">
    </form>  
  {% endif %}  
{% endblock %}